### ISSUE TITLE
bump gevent version >=1.0

### ISSUE THREAD

**Issue by zhouyuan** [ceph/s3-tests#78]
I find gevent 0.13.6 has several bugs on DNS resolving here. Is it possible to bump to the 1.0 version?

**Comment by zhouyuan** [comment]
I made some simple tests with s/spawn_link_exception/spawn, looks like it's working

here's the patch:
https://gist.github.com/zhouyuan/78dd28b41bef82fc9b3c

**Comment by caibo2014** [comment]
@zhouyuan  Only s3-tests have this problem?
I think teuthology many case failed  because of this reason too, how do you think?
顺便说一下，这个gist在我们公司打不开的。。。

**Comment by theanalyst** [comment]
@zhouyuan can you describe what dns problems you faced with s3-tests.. we are hitting a similar one on openstack

**Comment by zhouyuan** [comment]
@charpty @theanalyst 
This has been made a long time ago and I didn't have the detail error message now.
We actually don't have a real DNS server but using /etc/hosts in the testing cluster.
It's something like [this issue](https://github.com/gevent/gevent/issues/2) if my memory is right.

**Comment by theanalyst** [comment]
@zhouyuan would you mind making a pr with the contents of gist.. I;m inclined to try this out... we are facing the same issue with openstack nodes running s3-tests where we hit the DNSError, I don't want to spend a lot of time and conclude that gevent was the source of all troubles.. FYI, the issue is tracked here http://tracker.ceph.com/issues/13885

**Comment by zhouyuan** [comment]
closing with PR #104
